# Generated by Django 3.2.8 on 2021-10-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=40)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('image_link', models.CharField(max_length=32)),
                ('instagram', models.CharField(max_length=30)),
                ('line', models.CharField(max_length=32)),
            ],
        ),
    ]
