# Generated by Django 3.2.8 on 2021-10-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(default='sleep', max_length=200),
            preserve_default=False,
        ),
    ]
