# Generated by Django 3.2.8 on 2021-10-29 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 16, 51, 45, 693489, tzinfo=utc)),
        ),
    ]
