# Generated by Django 3.2.7 on 2021-10-30 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 9, 29, 7, 138202, tzinfo=utc)),
        ),
    ]
