# Generated by Django 3.2.8 on 2021-11-02 08:23

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2021, 11, 2, 8, 23, 0, 481083, tzinfo=utc)),
        ),
    ]
