# Generated by Django 3.2.9 on 2021-11-04 04:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211104_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 4, 2, 20, 371488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2021, 11, 4, 4, 2, 20, 370491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
