# Generated by Django 3.2.9 on 2021-11-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211103_1716'),
        ('main', '0020_auto_20211104_1429'),
    ]

    operations = [
    ]
