# Generated by Django 3.2.7 on 2021-11-05 03:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_merge_0017_auto_20211103_1716_0020_auto_20211104_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 3, 5, 24, 671027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2021, 11, 5, 3, 5, 24, 670238, tzinfo=utc)),
        ),
    ]
