# Generated by Django 3.2.7 on 2021-11-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20211105_1421'),
        ('main', '0025_auto_20211105_2130'),
    ]

    operations = [
    ]
