# Generated by Django 3.2.9 on 2021-12-30 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20211105_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 17, 33, 10, 150501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2021, 12, 30, 17, 33, 10, 149503, tzinfo=utc)),
        ),
    ]
